version: '3'
services:
  database:
    image: postgres:17.2
    container_name: depliants-manager-db
    environment:
      - POSTGRES_USER=dma
      - POSTGRES_PASSWORD=dma
      - POSTGRES_DB=dmadb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5445:5445"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER" ]
      interval: 30s
      timeout: 10s
      retries: 5
volumes:
  postgres_data: