version: '3'
services:
  database:
    image: postgres:17.2
    restart: unless-stopped
    container_name: depliants-manager-db
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5445:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER" ]
      interval: 30s
      timeout: 10s
      retries: 5
  service:
    image: ghcr.io/marcobelligoli/depliants-manager-app:latest
    restart: unless-stopped
    container_name: depliants-manager-service
    env_file:
      - .env
    ports:
      - "7271:8080"
    depends_on:
      - database
volumes:
  postgres_data: